'use strict';
const $=s=>document.querySelector(s);
let catalog=[],books=new Map(),current=null,page=1,texts=[],saved=[],last=null,loadId=0,textCache=new Map(),returnView='inicio';
const colors=['#f9d9d6','#ffd8c2','#ffedb3','#ddebc4','#d3e8f5','#e4daf2'];
const icons=['♧','◒','✿','⌂','☀','✦'];
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function readStore(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function writeStore(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch{toast('No se pudo guardar. Comprueba que el navegador permita almacenamiento.');return false}}
function validPosition(x){return x&&books.has(x.id)&&Number.isInteger(x.page)&&x.page>=1&&x.page<=books.get(x.id).pages}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('visible'),3000)}
function positionCard(x){const b=books.get(x.id);return `<article class="saved-card"><img src="library/${b.id}/${x.page}.webp" alt="" loading="lazy"><div class="saved-copy"><h3>${escapeHtml(b.group.title)}</h3><p>${escapeHtml(b.title)} · Página ${x.page} de ${b.pages}</p></div><button class="primary" data-read="${b.id}" data-page="${x.page}">Continuar →</button><button class="remove" data-remove="${b.id}:${x.page}" aria-label="Quitar marca de ${escapeHtml(b.group.title)}, página ${x.page}">×</button></article>`}
function resumeBlock(){const x=saved[0]||last;if(!x)return `<div class="resume"><div class="resume-icon">♡</div><div class="resume-copy"><strong>Tu próxima lectura empieza aquí</strong><p>Abre una guía y marca la página que quieras retomar.</p></div></div>`;const b=books.get(x.id);return `<div class="resume"><div class="resume-icon">♡</div><div class="resume-copy"><strong>${saved.length?'Dónde me quedé':'Tu última lectura'}</strong><p>${escapeHtml(b.group.title)} · ${escapeHtml(b.title)} · Página ${x.page}</p></div><button class="primary" data-read="${b.id}" data-page="${x.page}">Retomar lectura →</button></div>`}
function stageMarkup(g,i){return `<details class="stage" data-stage="${g.id}" style="--tint:${colors[i]}"><summary><span class="stage-icon" aria-hidden="true">${icons[i]}</span><div class="summary-copy"><h3>${escapeHtml(g.title)}</h3><p class="description">${escapeHtml(g.subtitle)}</p><p class="metadata">${g.books.length===1?'GUÍA COMPLETA':g.books.length+' PARTES'} · ${g.pages} PÁGINAS</p></div><span class="chevron" aria-hidden="true">⌄</span></summary><div class="parts">${g.books.map(b=>`<button class="part" data-read="${b.id}"><img src="library/${b.id}/1.webp" alt="" loading="lazy"><span class="part-copy">${escapeHtml(b.title)}<small>${b.pages} páginas · Leer aquí</small></span><span class="open-label">Abrir →</span></button>`).join('')}</div></details>`}
function bonusMarkup(){return `<div class="bonus-grid">${catalog.slice(6).map((g,i)=>`<button class="bonus" data-read="${g.books[0].id}"><span class="bonus-symbol" aria-hidden="true">${i?'☀':'▦'}</span><span><span class="eyebrow">BONO ${i+1} · INCLUIDO EN TU BIBLIOTECA</span><h3>${escapeHtml(g.title)}</h3><p>${i?'Ideas para esos días de pocas ganas y poco tiempo.':'Menús, listas de compras y organización semanal.'}</p><span class="bonus-action">Leer mi bono →</span></span></button>`).join('')}</div>`}
function dashboard(view='inicio'){
returnView=view;document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===view));
const footer=`<p class="footnote">Mi Infancia Saludable · Tu biblioteca, siempre a mano.<br>Las marcas y la última lectura se guardan en este navegador. Para conservarlas, usa el mismo dispositivo y no borres sus datos.</p>`;
let content='';
if(view==='guardados')content=`<p class="eyebrow">A TU RITMO</p><h1>Dónde me quedé</h1><p class="intro">Tus páginas marcadas, listas para volver cuando tengas un ratito.</p>${saved.length?`<div class="saved-list">${saved.map(positionCard).join('')}</div>`:'<div class="empty"><span style="font-size:38px">♡</span><h2>Todavía no marcaste una página</h2><p>Dentro de una guía, toca «Marcar esta página».<br>La encontrarás aquí la próxima vez que vuelvas.</p><a class="primary" href="#inicio">Explorar mi biblioteca</a></div>'}${last?`<div class="section-head"><h2>Última lectura</h2></div>${resumeBlockLast()}`:''}`;
else if(view==='bonos')content=`<p class="eyebrow">UN EXTRA PARA TU DÍA A DÍA</p><h1>Mis bonos</h1><p class="intro">Menos vueltas en la cocina. Más tiempo para disfrutar.</p><div class="section-head"><h2>Tus dos regalos</h2><span class="small-count">2 materiales</span></div>${bonusMarkup()}`;
else content=`<div class="welcome"><div><p class="eyebrow">BIENVENIDA A TU ESPACIO</p><h1>Crecer juntos,<br>un bocado a la vez.</h1><p class="intro">Tus guías, recetas y recursos, ordenados por etapa.<br>Elige dónde empezar. Nosotros te acompañamos.</p></div><div class="welcome-badge" aria-hidden="true">♧</div></div>${resumeBlock()}<div class="section-head"><div><h2>Una guía para cada etapa</h2><p>Toca una edad para desplegar su contenido.</p></div><span class="small-count">6 ETAPAS</span></div><input class="search" id="stage-search" type="search" aria-label="Buscar una etapa" placeholder="Buscar una etapa o guía…"><div class="stage-grid">${catalog.slice(0,6).map(stageMarkup).join('')}</div><p id="no-stages" class="highlight-note" hidden>No encontramos esa etapa. Prueba otra búsqueda.</p><div class="section-head"><div><h2>Un poquito de ayuda extra</h2><p>Tus bonos, incluidos y siempre a mano.</p></div><span class="small-count">2 BONOS</span></div>${bonusMarkup()}`;
$('#dashboard').innerHTML=content+footer;
$('#stage-search')?.addEventListener('input',e=>{const q=normalize(e.target.value);let count=0;document.querySelectorAll('[data-stage]').forEach(el=>{el.hidden=!normalize(el.textContent).includes(q);if(!el.hidden)count++});$('#no-stages').hidden=count>0});
}
function resumeBlockLast(){const b=books.get(last.id);return `<div class="resume"><div class="resume-copy"><strong>${escapeHtml(b.group.title)}</strong><p>${escapeHtml(b.title)} · Página ${last.page}</p></div><button class="primary" data-read="${last.id}" data-page="${last.page}">Continuar →</button></div>`}
const normalize=s=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
async function loadTexts(id){if(textCache.has(id))return textCache.get(id);const response=await fetch(`library/${id}/text.json`);if(!response.ok)throw Error('text');const data=await response.json();textCache.set(id,data);return data}
async function openBook(id,target=1){const b=books.get(id);if(!b)return;current=b;page=Math.min(b.pages,Math.max(1,Number(target)||1));$('#reader').hidden=false;document.body.style.overflow='hidden';$('#reader-title').textContent=b.group.title;$('#reader-subtitle').textContent=b.title;$('#page-total').textContent=`de ${b.pages}`;$('#page-number').max=b.pages;$('#book-search').value='';$('#search-results').textContent='';$('#page-stage').classList.remove('zoomed');$('#zoom').textContent='＋';texts=[];renderPage();$('#close-reader').focus();try{const t=await loadTexts(id);if(current?.id===id){texts=t;updateText()}}catch{if(current?.id===id)$('#accessible-text div').textContent='No se pudo cargar el texto. Puedes seguir leyendo la página.'}}
function updateText(){$('#accessible-text div').textContent=texts[page-1]||'Esta página no contiene texto extraíble. Consulta la imagen de la página.'}
function renderPage(){if(!current)return;const ticket=++loadId;$('#page-number').value=page;$('#prev').disabled=page===1;$('#next').disabled=page===current.pages;$('#page-status').hidden=false;$('#page-status').textContent='Cargando página…';$('#page-image').hidden=true;$('#page-image').alt=`${current.group.title}, ${current.title}, página ${page} de ${current.pages}`;$('#page-image').onload=()=>{if(ticket!==loadId)return;$('#page-status').hidden=true;$('#page-image').hidden=false};$('#page-image').onerror=()=>{if(ticket!==loadId)return;$('#page-status').textContent='No se pudo cargar la página. Comprueba tu conexión e inténtalo de nuevo.'};$('#page-image').src=`library/${current.id}/${page}.webp`;$('#page-stage').scrollTo(0,0);$('#accessible-text').open=false;updateText();$('.reader-progress span').style.width=`${page/current.pages*100}%`;last={id:current.id,page};writeStore('mis:last',last);updateSaveButton();if(page<current.pages){const img=new Image();img.src=`library/${current.id}/${page+1}.webp`}}
function changePage(next){if(!current||!Number.isFinite(next))return;const nextPage=Math.max(1,Math.min(current.pages,Math.trunc(next)));if(nextPage===page)return;page=nextPage;renderPage()}
function updateSaveButton(){const marked=saved.some(x=>x.id===current.id&&x.page===page);$('#save-page').textContent=marked?'✓ Página marcada':'♡ Marcar esta página'}
function closeReader(){$('#reader').hidden=true;current=null;loadId++;document.body.style.overflow='';dashboard(returnView);$('#main').focus();}
document.addEventListener('click',e=>{const read=e.target.closest('[data-read]');if(read){openBook(read.dataset.read,read.dataset.page||1);return}const remove=e.target.closest('[data-remove]');if(remove){const next=saved.filter(x=>`${x.id}:${x.page}`!==remove.dataset.remove);if(writeStore('mis:saved',next)){saved=next;dashboard('guardados');toast('Marca eliminada.')}}const result=e.target.closest('[data-result]');if(result)changePage(Number(result.dataset.result))});
$('#close-reader').onclick=closeReader;$('#prev').onclick=()=>changePage(page-1);$('#next').onclick=()=>changePage(page+1);$('#page-number').onchange=e=>{changePage(Number(e.target.value));e.target.value=page};$('#page-number').onkeydown=e=>{if(e.key==='Enter'){changePage(Number(e.target.value));e.target.blur()}};
$('#save-page').onclick=()=>{if(!current)return;const next=[{id:current.id,page},...saved.filter(x=>x.id!==current.id||x.page!==page)];if(writeStore('mis:saved',next)){saved=next;updateSaveButton();toast('Página guardada en «Dónde me quedé».')}};
$('#zoom').onclick=()=>{const zoomed=$('#page-stage').classList.toggle('zoomed');$('#zoom').textContent=zoomed?'−':'＋';$('#zoom').setAttribute('aria-label',zoomed?'Reducir página':'Ampliar página')};
$('#book-search').oninput=e=>{const q=normalize(e.target.value.trim());$('#search-results').innerHTML='';if(q.length<2)return;if(!texts.length){$('#search-results').textContent='El texto todavía está cargando. Vuelve a intentar en un momento.';return}const matches=texts.map((t,i)=>({t,i})).filter(x=>normalize(x.t).includes(q));$('#search-results').innerHTML=matches.length?matches.slice(0,40).map(x=>`<button class="search-result" data-result="${x.i+1}">Página ${x.i+1} →</button>`).join(''):'No encontramos ese texto en esta parte.'};
document.addEventListener('keydown',e=>{if(!current||['INPUT','TEXTAREA'].includes(e.target.tagName))return;if(e.key==='Escape')closeReader();if(e.key==='ArrowRight')changePage(page+1);if(e.key==='ArrowLeft')changePage(page-1)});
window.addEventListener('hashchange',()=>{if(current)closeReader();dashboard(['inicio','guardados','bonos'].includes(location.hash.slice(1))?location.hash.slice(1):'inicio');window.scrollTo(0,0)});
async function init(){try{const res=await fetch('catalog.json');if(!res.ok)throw Error('catalog');catalog=await res.json();catalog.forEach(g=>g.books.forEach(b=>books.set(b.id,{...b,group:g})));saved=readStore('mis:saved',[]);saved=Array.isArray(saved)?saved.filter(validPosition):[];const stored=readStore('mis:last',null);last=validPosition(stored)?stored:null;dashboard(['inicio','guardados','bonos'].includes(location.hash.slice(1))?location.hash.slice(1):'inicio')}catch{$('#dashboard').innerHTML='<div class="empty"><h1>No pudimos cargar tu biblioteca</h1><p>Comprueba tu conexión y vuelve a cargar la página.</p><button class="primary" onclick="location.reload()">Volver a intentar</button></div>'}}
init();
