const fractions={'¼':.25,'½':.5,'¾':.75,'⅓':1/3,'⅔':2/3,'⅛':.125,'⅜':.375,'⅝':.625,'⅞':.875};
const atom='(?:\\d+(?:[.,]\\d+)?(?:\\s*\\d+\\/\\d+|[¼½¾⅓⅔⅛⅜⅝⅞])?|\\d+\\/\\d+|[¼½¾⅓⅔⅛⅜⅝⅞])';
export function numeric(text){let t=text.trim().replace(',','.');let total=0;for(const [ch,value] of Object.entries(fractions)){if(t.includes(ch)){total+=value;t=t.replace(ch,'')}}if(t.includes('/')){const m=t.match(/^(?:(\d+)\s+)?(\d+)\/(\d+)$/);if(!m||Number(m[3])===0)return NaN;return total+Number(m[1]||0)+Number(m[2])/Number(m[3])}return total+Number(t||0)}
export function parseIngredient(raw){const source=raw.trim();const match=source.match(new RegExp(`^(${atom})(?:\\s*[–-]\\s*(${atom}))?\\s+(.+)$`));if(!match)return {raw:source,name:source,amount:null,max:null,unit:'',key:source.toLowerCase()};let name=match[3],unit='unidad';let amount=numeric(match[1]),max=match[2]?numeric(match[2]):null;const units=[['kg',/^(?:kg|kilogramos?)\b\s*(?:de\s+)?/i,1000,'g'],['g',/^(?:g|gramos?)\b\s*(?:de\s+)?/i,1,'g'],['ml',/^(?:ml|mililitros?)\b\s*(?:de\s+)?/i,1,'ml'],['l',/^(?:l|litros?)\b\s*(?:de\s+)?/i,1000,'ml'],['taza',/^tazas?\b\s*(?:de\s+)?/i,1,'taza'],['cucharadita',/^cucharaditas?\b\s*(?:de\s+)?/i,1,'cucharadita'],['cucharada',/^cucharadas?\b\s*(?:de\s+)?/i,1,'cucharada'],['rebanada',/^rebanadas?\b\s*(?:de\s+)?/i,1,'rebanada'],['diente',/^dientes?\b\s*(?:de\s+)?/i,1,'diente'],['hoja',/^hojas?\b\s*(?:de\s+)?/i,1,'hoja']];for(const [,pattern,multiplier,canonical] of units){if(pattern.test(name)){name=name.replace(pattern,'');amount*=multiplier;if(max!==null)max*=multiplier;unit=canonical;break}}if(/^de\s/.test(name)||!Number.isFinite(amount)||amount<=0)return {raw:source,name:source,amount:null,max:null,unit:'',key:source.toLowerCase()};name=name.trim();return {raw:source,name,amount,max,unit,key:name.toLowerCase().replace(/\s+/g,' ').replace(/^huevos\b/,'huevo').replace(/^bananas\b/,'banana')}}
export function splitIngredients(lines){return lines.flatMap(line=>line.split(/\s+y\s+(?=\d|[¼½¾⅓⅔⅛⅜⅝⅞])/)).map(parseIngredient)}
export function scaleIngredient(ingredient,factor){if(!Number.isFinite(factor)||factor<=0)throw Error('La cantidad debe ser mayor que cero.');return {...ingredient,amount:ingredient.amount===null?null:ingredient.amount*factor,max:ingredient.max===null?null:ingredient.max*factor}}
export function formatNumber(n){return new Intl.NumberFormat('es',{maximumFractionDigits:2}).format(n)}
export function formatIngredient(item){if(item.amount===null)return item.raw;const value=formatNumber(item.amount)+(item.max!==null?'–'+formatNumber(item.max):'');if(item.unit==='unidad')return `${value} ${item.amount===1&&item.max===null?'unidad':'unidades'} de ${item.name}`;const plural=item.amount===1&&item.max===null?'':'s';const unit=['g','ml'].includes(item.unit)?item.unit:item.unit+plural;return `${value} ${unit} de ${item.name}`}
export function scaledRecipe(recipe,target,repeats=1){if(!Number.isFinite(target)||target<=0||!Number.isFinite(repeats)||repeats<=0||!Number.isFinite(recipe.yield)||recipe.yield<=0)throw Error('Revisa las porciones y las preparaciones.');return splitIngredients(recipe.ingredients).map(x=>scaleIngredient(x,target/recipe.yield*repeats))}
export function consolidate(entries){const sums=new Map(),unmeasured=new Map();for(const {recipe,target,repeats} of entries){for(const item of scaledRecipe(recipe,target,repeats)){if(item.amount===null){unmeasured.set(item.key,item);continue}const key=`${item.key}|${item.unit}`;const previous=sums.get(key);if(previous){const minimum=previous.amount+item.amount;const maximum=(previous.max??previous.amount)+(item.max??item.amount);previous.amount=minimum;previous.max=Math.abs(maximum-minimum)<1e-9?null:maximum}else sums.set(key,{...item})}}return {measured:[...sums.values()].sort((a,b)=>a.name.localeCompare(b.name,'es')),unmeasured:[...unmeasured.values()].sort((a,b)=>a.name.localeCompare(b.name,'es'))}}
