import {scaledRecipe,consolidate,formatIngredient,formatNumber} from './kitchen-math.mjs';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normalize=s=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
let dataPromise;
export async function renderKitchen(container,{openBook,toast}){
container.innerHTML='<p class="eyebrow">MENOS CUENTAS, MÁS TIEMPO JUNTOS</p><h1>Mi calculadora de cocina</h1><p class="intro">Ajusta tus recetas y organiza la compra. Solo ingredientes y cantidades.</p><p role="status">Cargando las recetas de tu biblioteca…</p>';
try{
dataPromise??=fetch('recipes.json').then(r=>{if(!r.ok)throw Error('recipes');return r.json()}).catch(e=>{dataPromise=null;throw e});
const recipes=await dataPromise;
if(location.hash!=='#cocina')return;
const byId=new Map(recipes.map(r=>[r.id,r]));
let stored;try{stored=JSON.parse(localStorage.getItem('mis:kitchen-plan')||'[]')}catch{stored=[]}
let plan=Array.isArray(stored)?stored.filter(x=>byId.has(x.id)&&Number.isFinite(x.target)&&x.target>0&&x.target<=1000&&Number.isInteger(x.repeats)&&x.repeats>0&&x.repeats<=30):[];
let checked;try{checked=JSON.parse(localStorage.getItem('mis:kitchen-checked')||'[]')}catch{checked=[]}let ticks=new Set(Array.isArray(checked)?checked.filter(x=>typeof x==='string'):[]);
let current=recipes[0];
container.innerHTML=`<p class="eyebrow">MENOS CUENTAS, MÁS TIEMPO JUNTOS</p><h1>Mi calculadora de cocina</h1><p class="intro">Elige una receta, ajusta sus porciones y llévala a tu lista de compras.</p><div class="kitchen-layout"><section class="kitchen-card"><div class="kitchen-step"><span>1</span><h2>Elige qué vas a cocinar</h2></div><div class="kitchen-filters"><label>Etapa<select id="k-stage"><option value="">Todas las etapas</option>${[...new Map(recipes.map(r=>[r.stage,r.stageTitle]))].map(([id,title])=>`<option value="${id}">${esc(title)}</option>`).join('')}</select></label><label>Buscar receta<input id="k-search" type="search" placeholder="Avena, panqueques, lentejas…"></label></div><label class="kitchen-label">Receta<select id="k-recipe"></select></label><p id="k-matches" class="kitchen-help" aria-live="polite"></p><div id="k-detail"></div></section><aside class="kitchen-card kitchen-plan"><div class="kitchen-step"><span>2</span><h2>Tu lista de compras</h2></div><p class="kitchen-help">Agrega una o varias recetas. Sumamos las cantidades compatibles.</p><div id="k-plan"></div><div id="k-shopping"></div></aside></div><p class="footnote">Las cantidades salen de tus ebooks y se ajustan proporcionalmente. Se mantienen las indicaciones de variantes, ingredientes opcionales y uso familiar. Tazas, cucharadas, gramos y unidades se suman por separado cuando corresponde. Los ingredientes sin una medida numérica conservan el texto original.<br>Tu lista queda guardada en este navegador. No modifica las recomendaciones de edad ni de conservación de las guías.</p>`;
const get=s=>container.querySelector(s);
function persist(){try{localStorage.setItem('mis:kitchen-plan',JSON.stringify(plan));localStorage.setItem('mis:kitchen-checked',JSON.stringify([...ticks]));return true}catch{toast('No se pudo guardar la lista en este navegador.');return false}}
function choices(){const stage=get('#k-stage').value,q=normalize(get('#k-search').value.trim());const matches=recipes.filter(r=>(!stage||r.stage===stage)&&(!q||normalize(r.title).includes(q)));get('#k-recipe').innerHTML=matches.map(r=>`<option value="${r.id}">${esc(r.title)} · ${esc(r.stageTitle)}</option>`).join('');get('#k-matches').textContent=`${matches.length} recetas disponibles`;if(matches.length){current=matches.find(r=>r.id===current?.id)||matches[0];get('#k-recipe').value=current.id;detail()}else{current=null;get('#k-detail').innerHTML='<div class="kitchen-empty">No encontramos esa receta. Prueba otra palabra o etapa.</div>'}}
function detail(){get('#k-detail').innerHTML=`<div class="recipe-heading"><h3>${esc(current.title)}</h3><span class="pill">${esc(current.stageTitle)}</span></div><p class="kitchen-help">La receta original rinde <strong>${current.yield} ${esc(current.yieldUnit)}</strong>.</p><div class="kitchen-numbers"><label>Cantidad a preparar (${esc(current.yieldUnit)})<input id="k-target" type="number" min="0.25" max="1000" step="0.25" value="${current.yield}" inputmode="decimal"></label><label>Veces que prepararás esta receta<input id="k-repeats" type="number" min="1" max="30" step="1" value="1" inputmode="numeric"></label></div><p class="kitchen-help">Por ejemplo: 2 porciones, 5 veces = 10 porciones en total.</p><div id="k-adjusted" aria-live="polite"></div><div class="kitchen-actions"><button class="primary" id="k-add">＋ Agregar a mi lista</button><button class="secondary" id="k-source">Ver receta en el ebook ↗</button></div><details class="recipe-notes"><summary>Indicaciones de la receta original</summary><p>${esc(current.meta).replaceAll('\n','<br>')}</p>${current.storage?`<h4>Conservación según el ebook</h4><p>${esc(current.storage).replaceAll('\n','<br>')}</p>`:''}</details>`;get('#k-target').addEventListener('input',adjust);get('#k-repeats').addEventListener('input',adjust);get('#k-add').onclick=add;get('#k-source').onclick=()=>openBook(current.book,current.page);adjust()}
function values(){const target=Number(get('#k-target').value),repeats=Number(get('#k-repeats').value);return {target,repeats,valid:Number.isFinite(target)&&target>=.25&&target<=1000&&Number.isInteger(repeats)&&repeats>=1&&repeats<=30}}
function adjust(){const {target,repeats,valid}=values();get('#k-add').disabled=!valid;if(!valid){get('#k-adjusted').innerHTML='<p class="kitchen-error">Ingresa una cantidad entre 0,25 y 1.000, y de 1 a 30 preparaciones.</p>';return}const items=scaledRecipe(current,target,repeats);get('#k-adjusted').innerHTML=`<div class="amount-head"><strong>Ingredientes para ${formatNumber(target*repeats)} ${esc(current.yieldUnit)}</strong><small>${repeats} ${repeats===1?'preparación':'preparaciones'} × ${formatNumber(target)}</small></div><ul class="ingredient-list">${items.map(item=>`<li>${esc(formatIngredient(item))}${item.amount===null?'<small>Cantidad según la receta original</small>':''}</li>`).join('')}</ul>`}
function add(){const {target,repeats,valid}=values();if(!valid)return;const same=plan.find(x=>x.id===current.id&&x.target===target);if(same){if(same.repeats+repeats>30){toast('Esta receta ya alcanzó el máximo de 30 preparaciones.');return}same.repeats+=repeats}else{if(plan.length>=30){toast('Puedes organizar hasta 30 recetas en una lista.');return}plan.push({id:current.id,target,repeats})}persist();shopping();toast('Receta agregada a tu lista de compras.')}
function entries(){return plan.map(x=>({recipe:byId.get(x.id),target:x.target,repeats:x.repeats}))}
function listText(){const {measured,unmeasured}=consolidate(entries());return `MI INFANCIA SALUDABLE — LISTA DE COMPRAS\n\n${plan.map(x=>`${byId.get(x.id).title}: ${formatNumber(x.target)} ${byId.get(x.id).yieldUnit} × ${x.repeats}`).join('\n')}\n\nCANTIDADES\n${measured.map(x=>'□ '+formatIngredient(x)).join('\n')}\n\nSIN MEDIDA NUMÉRICA / SEGÚN LA RECETA\n${unmeasured.map(x=>'□ '+x.raw).join('\n')}\n\nRevisa las variantes, ingredientes opcionales y las indicaciones de la receta original.`}
function shopping(){get('#k-plan').innerHTML=plan.length?`<div class="plan-recipes">${plan.map((x,i)=>`<div class="plan-recipe"><span><strong>${esc(byId.get(x.id).title)}</strong><small>${formatNumber(x.target)} ${esc(byId.get(x.id).yieldUnit)} × ${x.repeats}</small></span><button class="round" data-remove-plan="${i}" aria-label="Quitar ${esc(byId.get(x.id).title)}">×</button></div>`).join('')}</div>`:'<div class="kitchen-empty"><span aria-hidden="true">▦</span><p>Tu lista empieza con una receta.<br>Elige una y toca «Agregar a mi lista».</p></div>';if(!plan.length){get('#k-shopping').innerHTML='';return}const {measured,unmeasured}=consolidate(entries());const row=(item,index)=>{const key=`${item.key}|${item.unit}|${formatIngredient(item)}`;return `<label class="shopping-row"><input type="checkbox" data-check-key="${esc(key)}" ${ticks.has(key)?'checked':''}><span>${esc(formatIngredient(item))}</span></label>`};get('#k-shopping').innerHTML=`<div class="amount-head"><strong>Tu compra, en una sola lista</strong><small>${plan.length} ${plan.length===1?'receta':'recetas'}</small></div><div>${measured.map(row).join('')}</div>${unmeasured.length?`<h3 class="unmeasured-title">Según la receta / a gusto</h3><p class="kitchen-help">No inventamos una cantidad para estos ingredientes.</p><div>${unmeasured.map(row).join('')}</div>`:''}<div class="kitchen-actions"><button class="primary" id="k-copy">Copiar lista</button><button class="secondary" id="k-download">Descargar lista</button></div>`;get('#k-copy').onclick=async()=>{try{await navigator.clipboard.writeText(listText());toast('Lista copiada. Puedes pegarla en tus notas.')}catch{toast('El navegador no permite copiar. Usa «Descargar lista».')}};get('#k-download').onclick=()=>{const url=URL.createObjectURL(new Blob([listText()],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='mi-lista-de-compras.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}
container.addEventListener('click',e=>{const remove=e.target.closest('[data-remove-plan]');if(remove){plan.splice(Number(remove.dataset.removePlan),1);persist();shopping()}},{signal:(()=>{const c=new AbortController();const observer=new MutationObserver(()=>{if(!container.querySelector('#k-stage')){c.abort();observer.disconnect()}});observer.observe(container,{childList:true});return c.signal})()});
container.addEventListener('change',e=>{if(e.target.matches('[data-check-key]')){if(e.target.checked)ticks.add(e.target.dataset.checkKey);else ticks.delete(e.target.dataset.checkKey);persist()}},{signal:(()=>{const c=new AbortController();const observer=new MutationObserver(()=>{if(!container.querySelector('#k-stage')){c.abort();observer.disconnect()}});observer.observe(container,{childList:true});return c.signal})()});
get('#k-stage').onchange=choices;get('#k-search').oninput=choices;get('#k-recipe').onchange=()=>{current=byId.get(get('#k-recipe').value);detail()};choices();shopping();
}catch{if(location.hash==='#cocina')container.innerHTML='<div class="empty"><h1>No pudimos cargar las recetas</h1><p>Comprueba tu conexión y vuelve a cargar la página.</p><button class="primary" onclick="location.reload()">Volver a intentar</button></div>'}}
